//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_15_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int IDAdmin { get; set; }
        public string TenAdmin { get; set; }
        public string IDTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
