//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_15_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        public int IDDangKy { get; set; }
        public Nullable<int> IDSinhVien { get; set; }
        public string IDHoatDong { get; set; }
        public Nullable<System.DateTime> ThoiGianDangKy { get; set; }
        public Nullable<System.DateTime> ThoiGianHuyDangKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HoatDong HoatDong { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
